---
title: "Conferences"
format: html
---

Below is a list of scientific conferences where works related to the SciK-Health project have been presented:

-   **ARS 2025 – Tenth International Workshop on Social Network Analysis** – University of Naples Federico II, Naples, 30–31 October 2025

-   **11th Social Science Methodology Conference of RC33** – University of Naples Federico II, Naples, 22–25 September 2025

-   **Futures of Sustainability – SIS/DIAS 2025** – University of Bari, Bari, 11–12 September 2025

-   **15th Scientific Meeting of the Classification and Data Analysis Group – CLADAG 2025** – University of Naples Federico II, Naples, 8–11 September 2025

-   **Innovation & Society: Statistics and Data Science for Evaluation and Quality – IES 2025 (SVQS, Italian Statistical Society)** – University of Padua, Bressanone, 25–27 June 2025

-   **ABC 2025 – Association for Business Communication: Building Bridges between Business Communication and Management** – Bergen, Norway, 3–6 June 2025

-   **5th Data Science and Social Research – DSSR 2025** – University of Chieti-Pescara “Gabriele D’Annunzio”, Pescara, 19–21 February 2025

-   **HEIRS Conference 2025 – “Civil Economy: an Old-New Paradigm”** – Rome, 31 January – 1 February 2025

-   **Enhancing Sustainability: Bridging Corporate Practices with Academic and Popular Discourse** – University of Napoli L’Orientale, Naples, 18–20 December 2024

-   **19th Annual Conference of the Italian Health Economics Association** – Digital Transformation in Healthcare, Naples, 9–10 December 2024

-   **28th International Conference on Science, Technology and Innovation Indicators – STI 2024** – Berlin, 18–20 September 2024

-   **Measuring and Interpreting World Changes with Statistics, Data Science and AI – ASA 2024** – Rome, 18–20 September 2024

-   **36th SIEP Conference 2024 – “Reimagining Welfare: Sustainable Paths in Public Finance”** – Cagliari, 12–13 September 2024

-   **26th International Conference on Computational Statistics – COMPSTAT 2024** – Justus-Liebig-University of Giessen, Germany, 27–30 August 2024

-   **17th International Conference on Statistical Analysis of Textual Data – JADT 2024** – Brussels, 25–27 June 2024

-   **52nd Scientific Meeting of the Italian Statistical Society – SIS 2024** – Bari, 17–20 June 2024

-   **4th International Conference on Data Science and Social Research – DSSR 2024** – Naples, 25–27 March 2024

-   **18th Annual Conference of the Italian Health Economics Association** – Value Generation in Healthcare Systems, Rome, 5–6 December 2023

-   **9th Italian Conference on Computational Linguistics – CLiC-it 2023** – Venice, 30 November – 2 December 2023
